[HxListLayout] Multiple DataTemplate sections + Tabs navigation #125
havit/Havit.Blazor pull request #146
Opened 2022-05-11 15:53 UTC by Harvey1214

The test page for this issue was created using only the functionality HxTabPanel offers at this time.

2022-05-13 12:22 UTC, hakenr commented
@crdo Can you continue on this PR?

2022-05-18 14:16 UTC, crdo commented
@hakenr ready for review and follow up.

2022-05-19 12:41 UTC, Harvey1214 commented
@crdo I was working on this issue before you committed the changes and I think it would be sounder to extract the different parts of the component into methods returning RenderFragments, so that the same code could be reused for Regular and Card mode. Let me know what you think, thanks for considering.
![Screenshot (356)](https://user-images.githubusercontent.com/62853076/169295195-e8c080a6-70f3-45f0-8e86-979fd9d2bac9.png)(note: "else if" will be used)

2022-05-19 15:13 UTC, hakenr reviewed
Extraction of the RenderFragments for better reusability?

e.g. https://www.syncfusion.com/faq/blazor/templated-components/how-do-you-define-a-render-fragment-using-a-razor-template-in-blazor

2022-05-20 06:49 UTC, crdo commented
> @crdo I was working on this issue before you committed the changes and I think it would be sounder to extract the different parts of the component into methods returning RenderFragments, so that the same code could be reused for Regular and Card mode. Let me know what you think, thanks for considering.
> ![Screenshot (356)](https://user-images.githubusercontent.com/62853076/169295195-e8c080a6-70f3-45f0-8e86-979fd9d2bac9.png)(note: "else if" will be used)

@Harvey1214 Sure thing. Already told @hakenr that there is a repeated code and it has to be refactored. You can go ahead.

2022-05-20 06:53 UTC, crdo commented on Havit.Blazor.Components.Web.Bootstrap/Navigation/HxTabPanelRenderMode.cs
> +		Standard = 0,
Tbh, `Standard` sounds better to me in this case but `Regular` for the other cases. If you want to unify, go ahead, I have no preference.

2022-05-20 07:09 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Navigation/HxTabPanelRenderMode.cs
> +		Standard = 0,
If there was no `Standard` up to now, I would go for `Regular`. For now, `Regular` sounds good for sizes and `Standard` for types/variations/kinds/etc.

2022-05-20 13:41 UTC, Harvey1214 commented
@crdo Do we want to handle the styling when NavVariant is set to Tabs? - set "padding-bottom: 0; border-bottom: 0;" on the card header, so that the tab navigation aligns to the content, or is it more suitable to let the users of the component adjust the CardSettings themselves (in that case, I suggest adding a demo to the docs).

2022-05-20 13:56 UTC, hakenr commented
@Harvey1214 / @crdo Please add standalone demo for new render-mode to [HxTabPanel](https://havit.blazor.eu/components/HxTabPanel) documentation (without HxListLayout).

2022-05-21 04:58 UTC, crdo commented
> @crdo Do we want to handle the styling when NavVariant is set to Tabs? - set "padding-bottom: 0; border-bottom: 0;" on the card header, so that the tab navigation aligns to the content, or is it more suitable to let the users of the component adjust the CardSettings themselves (in that case, I suggest adding a demo to the docs).

There is Bootstrap's class `card-header-tabs` for that.

2022-05-24 15:38 UTC, hakenr commented
@crdo  @Harvey1214 Merged master into this PR (branch)
Waiting for confirmation of DONE... :-D

2022-05-25 16:12 UTC, hakenr requested changes

2022-05-25 18:38 UTC, hakenr approved these changes
lgtm

2022-05-25 18:38 UTC, merged