[HxSidebar] HxSidebarItem ContentTemplate #212
havit/Havit.Blazor pull request #216
Opened 2022-06-17 15:16 UTC by Harvey1214

A new ContentTemplate parameter has been added to HxSidebarItem in order to allow custom content such as a HxBadge to be added to the items' contents.

ChildContent RenderFragment parameter (intended for sub-items) has been renamed to SubItems to comply with the library's conventions. The ChildContent parameter is currently still in function in order to continually prepare users for the breaking change.

2022-06-28 16:28 UTC, hakenr requested changes

2022-06-28 16:28 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor
>                          }
We should not replace the current item with the `ContentTemplate`, but add it to the other options (similar patter is used in other components where it makes sense).
I would go for order (chevron icon just for expandable items)
```
  @if ... <HxIcon />
  @ContentTemplate
  <span ...>@Text</span>
  <HxIcon Icon="@BootstrapIcon.ChevronRight" CssClass="expand-icon" />
```

2022-06-28 16:28 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor
> -                        <HxIcon Icon="@BootstrapIcon.ChevronRight" CssClass="expand-icon" />
We should not drop the chevron-icon for version with `@ContentTemplate`, see above.

2022-06-28 16:28 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor.cs
> +		}
Keep the parameter as `ChildContent` without the move to `SubItems`. I found this pattern in other libraries and makes sense for me. We might consolidate our other components later.

2022-06-28 16:29 UTC, hakenr commented
+ [ ] add demo with `ContentTemplate` usage, e.g. the badges requested.

2022-06-29 13:29 UTC, Harvey1214 commented
@hakenr Do we want to automatically hide the ContentTemplate when a sidebar is collapsed? Currently, it is always rendered, which leaves it up to the user to handle the hiding that I don't find ideal. Please let me know what you think, thanks.

2022-06-29 22:42 UTC, hakenr commented
Ahh, I see. The visibility of the item-content is currently bound to `.text` class. If it is a custom class, let's rename it to `.hx-sidebar-item-content` and arrange the HTML like this:
```razor
<div class="hx-sidebar-item-content ..">
  @Text
  @ContentTemplate      
</div>
```
@crdo?

2022-07-01 13:02 UTC, hakenr approved these changes
lgtm, the other issues will be resolved in separate ticker

2022-07-01 13:28 UTC, merged