[HxGrid] A way to persist grid state (sorting, current page) ? #360
havit/Havit.Blazor pull request #385
Opened 2022-09-19 11:23 UTC by jirikanda

2022-09-19 11:27 UTC, jirikanda commented
Next step: Rename SortingItem<TItem> to GridSortingItem<TItem> while it contains grid specific property (SortDefaultOrder).

2022-09-26 13:37 UTC, jirikanda commented
Work in progress...
TODO: Unit test, naming (and small refactorings).
(Renaming SortingItem to GridSortingItem not required anymore, SortDefaultOrder property removed.)

2022-11-08 13:40 UTC, hakenr requested changes
lgtm, naming adjustments only

2022-11-08 13:40 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Grids/HxGridColumnBase.cs
> +	protected abstract string GetColumnIdentifier();
@jirikanda `GetColumnId()` to align with the `Id` parameter?

2022-11-08 13:40 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Grids/IHxGridColumn.cs
> +	string GetIdentifier();
`GetId()`?

2022-11-08 14:04 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor.cs
> +	private HashSet<string> columnIds;
@jirikanda Not being used

2022-11-08 15:21 UTC, hakenr approved these changes
lgtm, merging

2022-11-08 15:22 UTC, merged