[HxSearchBox] Search icon missaligned when used with label #487
havit/Havit.Blazor pull request #489
Opened 2023-03-03 17:39 UTC by Harvey1214

2023-03-04 22:21 UTC, hakenr requested changes
There are some minor adjustments needed from coding point of view.
@crdo, can you please review the HTML/CSS?

2023-03-06 09:39 UTC, crdo commented
I don't like the way the HxSearch is implemented from the structure POV.
It is very similar as the HxAutosuggest that supports clear/search icon with input groups but here, we turn icons off if inputs are used. I think these two should be aligned.
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/1410922/223072726-4940d4b5-95a1-4c96-b764-d62ec2b1c17c.png">

2023-03-06 13:06 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor
> +                       (ShowSearchIconEffective && HasInputGroupsEffective ? "hx-search-box-input-with-search-icon" : null),
@Harvey1214 It seems the `.hx-search-box-input-with-search-icon` is no longer defined. Might lead to simplification (elimination) of the properties above.

2023-03-17 14:35 UTC, Harvey1214 commented on Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor.css
> -::deep .hx-search-box-input-with-search-icon {
@crdo this class is necessary when `InputGroupStartText` or `InputGroupStartTemplate` is set because otherwise the corners aren't rounded.

2023-03-17 14:36 UTC, Harvey1214 commented
> I don't like the way the HxSearch is implemented from the structure POV. It is very similar as the HxAutosuggest that supports clear/search icon with input groups but here, we turn icons off if inputs are used. I think these two should be aligned. <img alt="image" width="1011" src="https://user-images.githubusercontent.com/1410922/223072726-4940d4b5-95a1-4c96-b764-d62ec2b1c17c.png">

That's a good point, however, I'd suggest creating a different issue for this matter.

2023-03-28 13:44 UTC, merged