fixed #621 [HxInputDate] Add CalendarDisplayMonth
havit/Havit.Blazor pull request #626
Opened 2023-10-16 13:34 UTC by blanchardglen

[HxInputDateRange] Bug ToInputDateRange displays the From selected date
Add FromCalendarDisplayMonth and ToCalendarDisplayMonth
The To calendar will choose the latest of the FromDate or ToCalendarDisplayMonth or if both are not set then the FromCalendarDisplayMonth

Any changes required please let me know.

2023-10-19 10:28 UTC, hakenr requested changes
I think, if there is a `Value`, it should be always used for displayed month. The new parameters should be effective only when there is no `Value` present. (Separate behavior for `From`/`To` in `HxInputDateRange`).

2023-10-19 10:28 UTC, hakenr commented on BlazorAppTest/Pages/HxInputDate_Issue621_Test.razor
> +    private DateTimeRange Unset;
`camelCase` for private fields.

2023-10-19 10:28 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateRangeInternal.razor.cs
> +	private DateTime toCalendarDisplayMonthEffective
Please make this a method called `GetToCalendarDisplayMonthEffective()`

2023-10-20 03:54 UTC, blanchardglen commented
> I think, if there is a `Value`, it should be always used for displayed month. The new parameters should be effective only when there is no `Value` present. (Separate behavior for `From`/`To` in `HxInputDateRange`).

The HxCalendar takes care of this already in my testing, please correct me if I am wrong though.

The only minor complexity is in the `GetToCalendarDisplayMonthEffective` for `HxInputDateRange`  because the `From` value might override the `ToCalendarDisplayMonth` but only if it is less than the provided `ToCalendarDisplayMonth`

I would imagine the vast majority of times the `ToCalendarDisplayMonth` would never be set, in that case should it be removed?

2023-10-24 11:02 UTC, hakenr commented
Current behavior to fix (calendar resets to `DisplayMonth` although there is `Value` from previous month):
![2023-10-24_13-00-34](https://github.com/havit/Havit.Blazor/assets/12828888/41b53020-eb61-4bc7-b258-735913972c7e)

2023-10-24 11:04 UTC, hakenr commented
> I would imagine the vast majority of times the `ToCalendarDisplayMonth` would never be set, in that case should it be removed?

As you already implemented it, if the `Value` will have precedence, let's keep the `ToCalendarDisplayMonth` for those rare cases when you expect the range to end in some specific month in future 🤷‍♂️.

2023-10-24 21:07 UTC, blanchardglen commented
Thanks for your patience!

Adjusted for `Value` to take precedence in `HxInputDate` and both `From` and `To` parts of `HxInputDateRange`

2023-10-24 22:24 UTC, hakenr approved these changes
lgtm

2023-10-24 22:24 UTC, merged