[HxMultiSelect] Select all synchronisation
havit/Havit.Blazor pull request #639
Opened 2023-10-28 00:51 UTC by bholbrook

# Summary of changes
- As per #638:
  - Select all now syncs upon item selection and filter input changes
  -  Select all now automatically checks if `Value` contains all items

2023-10-28 00:58 UTC, tsengsy commented on Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxMultiSelectInternal.razor.cs
> +			selectAllChecked = false;
Do you have to handle the opposite as well?

```
if (!selectAllChecked)
```

2023-10-31 14:15 UTC, bholbrook commented
@hakenr @crdo Could I please have this reviewed?

2023-10-31 23:29 UTC, hakenr requested changes
@bholbrook Oops, sorry, I forgot to submit the review.

2023-11-01 12:49 UTC, bholbrook commented on Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxMultiSelectInternal.razor.cs
> +		}
1. I wrote slightly logic for `HandleFilterInputChanged` vs `HandleItemSelectionChangedAsync` as the `SelectedValues` field isn't in the same state for both cases.
In `HandleItemSelectionChangedAsync` it hasn't yet added the selected value to the list and so the sync wouldn't work without a temporary concatenation, but we also don't want to add it to the `SelectedValues` field in there as it'd require rework. We can also simplify some cases like when you're selecting the only available option in the dropdown to slightly improve performance albeit somewhat negligible.
In `HandleFilterInputChanged` the state of `SelectedValues` is complete and so we can compare the entire list as is.

I'm not sure how a single shared function such as a `SynchronizeSelectAllCheckbox` would functionally work. If you have any ideas I'd be happy to trial them.

2. I have added conditions to improve performance when select all is disabled.

3. I have changed the main conditions to utilise `.Any()`

2023-11-01 12:49 UTC, bholbrook commented on Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxMultiSelectInternal.razor.cs
> +
I have moved this logic into `OnParametersSet`.

2023-11-01 12:50 UTC, bholbrook commented
@hakenr I've made changes as per your review and am ready for a re-review.

2023-11-01 16:24 UTC, hakenr approved these changes
@bholbrook I did some final adjustments and will merge to master.
- simplified the logic (sacrificed some of the perf-optimizations for now)
- extracted the `SynchronizeSelectAllCheckbox()` method
- fixed: ClearIcon did not synchronize the checkbox
I will probably simplify the `SelectedValues` synchronization with outer `HxMultiSelect` then.

Many thanks for your contribution!
We will add additional pre-release the lib today.
We plan to publish the 4.2.5 release later this week.

2023-11-01 16:24 UTC, merged