HxDropdownItem - add Icon parameter, default and documentation
havit/Havit.Blazor pull request #655
Opened 2023-11-09 20:53 UTC by vaclavek

I noticed that the property 'Icon' is missing on HxDropdownItem. I added the property as it is implemented in HxContextMenuItem, including the CSS variable and documentation. Is there anything else I should do? :)

2023-11-09 23:20 UTC, hakenr requested changes
The `HxDropdownItem` is intended to be a "bare" Bootstrap component, and icons can be readily incorporated via the `ChildContent`. This is in contrast to `HxContextMenuItem`, which is a more comprehensive component that we define. Conversely, the `HxButton` does feature an `Icon` property. We could offer these enhancements to simplify the use of our component library.

However, I'm curious as to why you opted for `HxDropdownItem` to add the `Icon` property. Should this functionality also extend to `HxDropdownItemNavLink` and `HxDropdownItemText`? Perhaps even to `HxDropdownHeader`?

cc @crdo

2023-11-09 23:20 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/wwwroot/defaults.css
> +	--hx-dropdown-menu-item-icon: 									0 .5rem 0 0;
This should be named `--hx-dropdown-menu-item-icon-margin` (see the `HxContextMenuItem` variable few lines above).

2024-06-26 05:34 UTC, crdo commented
@vaclavek yes please. At least for HxDropdownItemText and HxDropdownItemNavLink.

2024-07-26 15:23 UTC, fejfailo commented
Hi @crdo and @hakenr,

I have added the Icon to the HxDropdownItemText, HxDropdownItemNavLink, and HxDropdownHeader components as requested. To be able to reuse the icon in the dropdown items component, I have added an internal component, HxDropdownIcon.

From my side, it is ready for review.

2024-07-26 15:24 UTC, vaclavek commented
Hi @crdo and @hakenr,

I have added the Icon to the HxDropdownItemText, HxDropdownItemNavLink, and HxDropdownHeader components as requested. To be able to reuse the icon in the dropdown items component, I have added an internal component, HxDropdownIcon.

From my side, it is ready for review

2024-08-30 14:43 UTC, hakenr approved these changes
lgtm (did some minor adjustments and merging)

2024-08-30 14:43 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Dropdowns/Internal/HxDropdownIcon.razor.cs
> +public partial class HxDropdownIcon : ComponentBase
All internal components share the `Internal` suffix in name.

2024-08-30 14:43 UTC, hakenr commented on Havit.Blazor.Components.Web.Bootstrap/Dropdowns/Internal/HxDropdownIcon.razor.cs
> +	[Parameter] public string IconCssClass { get; set; }
Renaming to `CssClass`.

2024-08-30 14:43 UTC, hakenr commented on Havit.Blazor.Documentation/Pages/Components/HxDropdownDoc/HxDropdown_Demo_WithIcons.razor
> +    <HxDropdownMenu CssClass="dropdown-menu-dark">
I will remove the "dark"-feature from this demo.

2024-08-30 14:45 UTC, merged